[package]
name = "uniffi_meta"
version = "0.17.0"
edition = "2021"

[dependencies]
fs-err = "2.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
syn = { version = "1.0", features = ["full"] }
